In [1]:
import requests
import pandas as pd
from pathlib import Path
import os
import io

In [2]:
base_url = "https://www.football-data.co.uk"
en_base_url = f"{base_url}/mmz4281"
en_2425_url = f"{en_base_url}/2425v"
en_2425_pl_url = f"{en_2425_url}/E0.csv"

In [3]:
resp = requests.get(en_2425_pl_url)
data = resp.content.decode('utf-8')

df = pd.read_csv(io.StringIO(data))
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

In [4]:
type(df.columns.values)
df.columns.values

array(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG',
       'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST',
       'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D',
       'B365A', 'BWH', 'BWD', 'BWA', 'BFH', 'BFD', 'BFA', 'PSH', 'PSD',
       'PSA', 'WHH', 'WHD', 'WHA', '1XBH', '1XBD', '1XBA', 'MaxH', 'MaxD',
       'MaxA', 'AvgH', 'AvgD', 'AvgA', 'BFEH', 'BFED', 'BFEA', 'B365>2.5',
       'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5',
       'Avg<2.5', 'BFE>2.5', 'BFE<2.5', 'AHh', 'B365AHH', 'B365AHA',
       'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'BFEAHH',
       'BFEAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA',
       'BFCH', 'BFCD', 'BFCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD',
       'WHCA', '1XBCH', '1XBCD', '1XBCA', 'MaxCH', 'MaxCD', 'MaxCA',
       'AvgCH', 'AvgCD', 'AvgCA', 'BFECH', 'BFECD', 'BFECA', 'B365C>2.5',
       'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5',
       'AvgC>2.5', 'AvgC<2.5', 'BFEC>2.5', 'BFEC<2.5', 'AHCh', 'B365CAHH',
       'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH',
       'AvgCAHA', 'BFECAHH', 'BFECAHA'], dtype=object)

In [8]:
df["HomeTeam"].unique()

array(['Man United', 'Ipswich', 'Arsenal', 'Everton', 'Newcastle',
       "Nott'm Forest", 'West Ham', 'Brentford', 'Chelsea', 'Leicester',
       'Brighton', 'Crystal Palace', 'Fulham', 'Man City', 'Southampton',
       'Tottenham', 'Aston Villa', 'Bournemouth', 'Wolves', 'Liverpool'],
      dtype=object)

In [16]:
df[(df.HomeTeam == "Brighton") | (df.AwayTeam == "Brighton")]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
10,E0,24/08/2024,12:30,Brighton,Man United,2,1,H,1,0,...,2.07,1.86,2.12,1.83,2.20,1.86,2.09,1.79,2.15,1.85
20,E0,31/08/2024,12:30,Arsenal,Brighton,1,1,D,1,0,...,2.08,1.85,2.09,1.85,2.12,1.86,2.05,1.83,2.14,1.86
31,E0,14/09/2024,15:00,Brighton,Ipswich,0,0,D,0,0,...,1.87,2.06,1.89,2.04,1.89,2.16,1.80,2.10,1.83,2.19

In [25]:
df = df[['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS','HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']]
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,5,2,12,10,7,8,2,3,0,0
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2,5,9,18,2,10,3,1,0,0
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,6,3,17,14,8,2,2,2,0,0
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1,5,8,8,1,5,1,1,1,0
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1,4,15,16,3,12,2,4,1,0

In [35]:
## Extract data for one team

In [37]:
team = "Brighton"

dft = df[(df.HomeTeam == team) | (df.AwayTeam == team)]
dft

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1,5,8,8,1,5,1,1,1,0
10,E0,24/08/2024,12:30,Brighton,Man United,2,1,H,1,0,...,5,4,9,13,4,4,1,2,0,0
20,E0,31/08/2024,12:30,Arsenal,Brighton,1,1,D,1,0,...,7,4,12,7,3,7,3,2,1,0
31,E0,14/09/2024,15:00,Brighton,Ipswich,0,0,D,0,0,...,6,1,14,16,9,2,4,3,0,0

In [45]:
dft['Date'] = pd.to_datetime(dft['Date'], format='%d/%m/%Y')

/tmp/ipykernel_41/683982175.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dft['Date'] = pd.to_datetime(dft['Date'], format='%d/%m/%Y')
/tmp/ipykernel_41/683982175.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dft.drop('TheDate', inplace=True, axis=1)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
3,E0,2024-08-17,15:00,Everton,Brighton,0,3,A,0,1,...,1,5,8,8,1,5,1,1,1,0
10,E0,2024-08-24,12:30,Brighton,Man United,2,1,H,1,0,...,5,4,9,13,4,4,1,2,0,0
20,E0,2024-08-31,12:30,Arsenal,Brighton,1,1,D,1,0,...,7,4,12,7,3,7,3,2,1,0
31,E0,2024-09-14,15:00,Brighton,Ipswich,0,0,D,0,0,...,6,1,14,16,9,2,4,3,0,0

In [59]:
dft = dft.sort_values(by = 'Date', ascending=True)

In [61]:
dft['Home'] = dft.HomeTeam == team
dft

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Home
3,E0,2024-08-17,15:00,Everton,Brighton,0,3,A,0,1,...,5,8,8,1,5,1,1,1,0,False
10,E0,2024-08-24,12:30,Brighton,Man United,2,1,H,1,0,...,4,9,13,4,4,1,2,0,0,True
20,E0,2024-08-31,12:30,Arsenal,Brighton,1,1,D,1,0,...,4,12,7,3,7,3,2,1,0,False
31,E0,2024-09-14,15:00,Brighton,Ipswich,0,0,D,0,0,...,1,14,16,9,2,4,3,0,0,True

In [63]:
def get_y(df):
    if (df.Home):
        return df.FTR.shift()
    else:
        df.FTR.shift()



dft['Y'] = df.FTR.shift()
dft

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HF,AF,HC,AC,HY,AY,HR,AR,Home,Y
3,E0,2024-08-17,15:00,Everton,Brighton,0,3,A,0,1,...,8,8,1,5,1,1,1,0,False,H
10,E0,2024-08-24,12:30,Brighton,Man United,2,1,H,1,0,...,9,13,4,4,1,2,0,0,True,D
20,E0,2024-08-31,12:30,Arsenal,Brighton,1,1,D,1,0,...,12,7,3,7,3,2,1,0,False,H
31,E0,2024-09-14,15:00,Brighton,Ipswich,0,0,D,0,0,...,14,16,9,2,4,3,0,0,True,A

In [58]:
from datetime import datetime

# dft.drop('Rest', inplace=True, axis=1)

# dft['Rest'] = datetime.now() - dft.Date
dft

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Home
31,E0,2024-09-14,15:00,Brighton,Ipswich,0,0,D,0,0,...,1,14,16,9,2,4,3,0,0,True
20,E0,2024-08-31,12:30,Arsenal,Brighton,1,1,D,1,0,...,4,12,7,3,7,3,2,1,0,False
10,E0,2024-08-24,12:30,Brighton,Man United,2,1,H,1,0,...,4,9,13,4,4,1,2,0,0,True
3,E0,2024-08-17,15:00,Everton,Brighton,0,3,A,0,1,...,5,8,8,1,5,1,1,1,0,False