In [1]:
import requests
import pandas as pd
from pathlib import Path
import os
import io

In [45]:
base_url = "https://www.football-data.co.uk"
en_base_url = f"{base_url}/mmz4281"
en_2425_url = f"{en_base_url}/2425v"
en_2425_pl_url = f"{en_2425_url}/E0.csv"

In [46]:
resp = requests.get(en_2425_pl_url)
data = resp.content.decode('utf-8')

df = pd.read_csv(io.StringIO(data))
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10

In [47]:
type(df.columns.values)
df.columns.values

array(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG',
       'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST',
       'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D',
       'B365A', 'BWH', 'BWD', 'BWA', 'BFH', 'BFD', 'BFA', 'PSH', 'PSD',
       'PSA', 'WHH', 'WHD', 'WHA', '1XBH', '1XBD', '1XBA', 'MaxH', 'MaxD',
       'MaxA', 'AvgH', 'AvgD', 'AvgA', 'BFEH', 'BFED', 'BFEA', 'B365>2.5',
       'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5',
       'Avg<2.5', 'BFE>2.5', 'BFE<2.5', 'AHh', 'B365AHH', 'B365AHA',
       'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'BFEAHH',
       'BFEAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA',
       'BFCH', 'BFCD', 'BFCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD',
       'WHCA', '1XBCH', '1XBCD', '1XBCA', 'MaxCH', 'MaxCD', 'MaxCA',
       'AvgCH', 'AvgCD', 'AvgCA', 'BFECH', 'BFECD', 'BFECA', 'B365C>2.5',
       'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5',
       'AvgC>2.5', 'AvgC<2.5', 'BFEC>2.5', 'BFEC<2.5', 'AHCh', 'B365CAHH',
       'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH',
       'AvgCAHA', 'BFECAHH', 'BFECAHA'], dtype=object)

In [5]:
df["HomeTeam"].unique()

array(['Man United', 'Ipswich', 'Arsenal', 'Everton', 'Newcastle',
       "Nott'm Forest", 'West Ham', 'Brentford', 'Chelsea', 'Leicester',
       'Brighton', 'Crystal Palace', 'Fulham', 'Man City', 'Southampton',
       'Tottenham', 'Aston Villa', 'Bournemouth', 'Wolves', 'Liverpool'],
      dtype=object)

In [6]:
df[(df.HomeTeam == "Brighton") | (df.AwayTeam == "Brighton")]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
10,E0,24/08/2024,12:30,Brighton,Man United,2,1,H,1,0,...,2.07,1.86,2.12,1.83,2.20,1.86,2.09,1.79,2.15,1.85
20,E0,31/08/2024,12:30,Arsenal,Brighton,1,1,D,1,0,...,2.08,1.85,2.09,1.85,2.12,1.86,2.05,1.83,2.14,1.86
31,E0,14/09/2024,15:00,Brighton,Ipswich,0,0,D,0,0,...,1.87,2.06,1.89,2.04,1.89,2.16,1.80,2.10,1.83,2.19

In [7]:
df = df[['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS','HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']]
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,5,2,12,10,7,8,2,3,0,0
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2,5,9,18,2,10,3,1,0,0
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,6,3,17,14,8,2,2,2,0,0
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1,5,8,8,1,5,1,1,1,0
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1,4,15,16,3,12,2,4,1,0

## Extract data for one team

In [8]:
team = "Brighton"

dft = df[(df.HomeTeam == team) | (df.AwayTeam == team)]
dft

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1,5,8,8,1,5,1,1,1,0
10,E0,24/08/2024,12:30,Brighton,Man United,2,1,H,1,0,...,5,4,9,13,4,4,1,2,0,0
20,E0,31/08/2024,12:30,Arsenal,Brighton,1,1,D,1,0,...,7,4,12,7,3,7,3,2,1,0
31,E0,14/09/2024,15:00,Brighton,Ipswich,0,0,D,0,0,...,6,1,14,16,9,2,4,3,0,0

In [9]:
dft['Date'] = pd.to_datetime(dft['Date'], format='%d/%m/%Y')

/tmp/ipykernel_947/134357352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dft['Date'] = pd.to_datetime(dft['Date'], format='%d/%m/%Y')

In [10]:
dft = dft.sort_values(by = 'Date', ascending=True)

In [11]:
dft['Home'] = dft.HomeTeam == team
dft

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Home
3,E0,2024-08-17,15:00,Everton,Brighton,0,3,A,0,1,...,5,8,8,1,5,1,1,1,0,False
10,E0,2024-08-24,12:30,Brighton,Man United,2,1,H,1,0,...,4,9,13,4,4,1,2,0,0,True
20,E0,2024-08-31,12:30,Arsenal,Brighton,1,1,D,1,0,...,4,12,7,3,7,3,2,1,0,False
31,E0,2024-09-14,15:00,Brighton,Ipswich,0,0,D,0,0,...,1,14,16,9,2,4,3,0,0,True

In [12]:
# def get_y(row):
#     if pd.isna(row.name) or row.name==0:
#         return None
#     else:
        
#     if (df.Home):
#         return df.FTR.shift()
#     else:
#         df.FTR.shift()



# dft['Y'] = df.apply()
# dft

In [14]:
# from datetime import datetime

# dft.drop('Rest', inplace=True, axis=1)

# dft['Rest'] = datetime.now() - dft.Date
# dft

## What data is needed

### For the home team:

* num of games played in the season home / away
* num of wins home / away
* num of wins home / away half time
* position on the table
* last year division
* last year position on the table
* median - HT_FTHG
* median - HT_HTHG
* median - HT_HS
* median - HT_HST
* median - HT_HHW
* median - HT_HC
* median - HT_HF
* median - HT_HFKC
* median - HT_HO
* median - HT_HY
* median - HT_HR
* median - HT_FTAG
* median - HT_HTAG
* median - HT_AS
* median - HT_AST
* median - HT_AHW
* median - HT_AC
* median - HT_AF
* median - HT_AFKC
* median - HT_AO
* median - HT_AY
* median - HT_AR


## For the away team
* num of games played in the season home / away
* num of wins home / away
* num of wins home / away half time
* position on the table
* last year division
* last year position on the table
* median - AT_FTHG
* median - AT_HTHG
* median - AT_HS
* median - AT_HST
* median - AT_HHW
* median - AT_HC
* median - AT_HF
* median - AT_HFKC
* median - AT_HO
* median - AT_HY
* median - AT_HR
* median - AT_FTAG
* median - AT_HTAG
* median - AT_AS
* median - AT_AST
* median - AT_AHW
* median - AT_AC
* median - AT_AF
* median - AT_AFKC
* median - AT_AO
* median - AT_AY
* median - AT_AR

In [40]:
teams = df.HomeTeam.unique().tolist()
teams
df.index = pd.MultiIndex.from_arrays([df.HomeTeam, df.Date], )
df = df.sort_index()
df.loc["Arsenal"]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
Date,,,,,,,,,,,,,,,,,,,,,
17/08/2024,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,6,3,17,14,8,2,2,2,0,0
31/08/2024,E0,31/08/2024,12:30,Arsenal,Brighton,1,1,D,1,0,...,7,4,12,7,3,7,3,2,1,0

In [50]:
dfa = df.groupby("HomeTeam").mean()
dfa

TypeError: agg function failed [how->mean,dtype->object]

In [41]:
df

                          Div        Date   Time        HomeTeam  \
HomeTeam       Date
Arsenal        17/08/2024  E0  17/08/2024  15:00         Arsenal
               31/08/2024  E0  31/08/2024  12:30         Arsenal
Aston Villa    14/09/2024  E0  14/09/2024  17:30     Aston Villa
               24/08/2024  E0  24/08/2024  17:30     Aston Villa
Bournemouth    14/09/2024  E0  14/09/2024  20:00     Bournemouth
               25/08/2024  E0  25/08/2024  14:00     Bournemouth
Brentford      18/08/2024  E0  18/08/2024  14:00       Brentford
               31/08/2024  E0  31/08/2024  15:00       Brentford
Brighton       14/09/2024  E0  14/09/2024  15:00        Brighton
               24/08/2024  E0  24/08/2024  12:30        Brighton
Chelsea        01/09/2024  E0  01/09/2024  13:30         Chelsea
               18/08/2024  E0  18/08/2024  16:30         Chelsea
Crystal Palace 14/09/2024  E0  14/09/2024  15:00  Crystal Palace
               24/08/2024  E0  24/08/2024  15:00  Crystal Palace
Everton        17/08/2024  E0  17/08/2024  15:00         Everton
               31/08/2024  E0  31/08/2024  15:00         Everton
Fulham         14/09/2024  E0  14/09/2024  15:00          Fulham
               24/08/2024  E0  24/08/2024  15:00          Fulham
Ipswich        17/08/2024  E0  17/08/2024  12:30         Ipswich
               31/08/2024  E0  31/08/2024  15:00         Ipswich
Leicester      19/08/2024  E0  19/08/2024  20:00       Leicester
               31/08/2024  E0  31/08/2024  15:00       Leicester
Liverpool      14/09/2024  E0  14/09/2024  15:00       Liverpool
               25/08/2024  E0  25/08/2024  16:30       Liverpool
Man City       14/09/2024  E0  14/09/2024  15:00        Man City
               24/08/2024  E0  24/08/2024  15:00        Man City
Man United     01/09/2024  E0  01/09/2024  16:00      Man United
               16/08/2024  E0  16/08/2024  20:00      Man United
Newcastle      01/09/2024  E0  01/09/2024  13:30       Newcastle
               17/08/2024  E0  17/08/2024  15:00       Newcastle
Nott'm Forest  17/08/2024  E0  17/08/2024  15:00   Nott'm Forest
               31/08/2024  E0  31/08/2024  15:00   Nott'm Forest
Southampton    14/09/2024  E0  14/09/2024  12:30     Southampton
               24/08/2024  E0  24/08/2024  15:00     Southampton
Tottenham      15/09/2024  E0  15/09/2024  14:00       Tottenham
               24/08/2024  E0  24/08/2024  15:00       Tottenham
West Ham       17/08/2024  E0  17/08/2024  17:30        West Ham
               31/08/2024  E0  31/08/2024  17:30        West Ham
Wolves         15/09/2024  E0  15/09/2024  16:30          Wolves
               25/08/2024  E0  25/08/2024  14:00          Wolves

                                 AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  ...  \
HomeTeam       Date                                                    ...
Arsenal        17/08/2024          Wolves     2     0   H     1     0  ...
               31/08/2024        Brighton     1     1   D     1     0  ...
Aston Villa    14/09/2024         Everton     3     2   H     1     2  ...
               24/08/2024         Arsenal     0     2   A     0     0  ...
Bournemouth    14/09/2024         Chelsea     0     1   A     0     0  ...
               25/08/2024       Newcastle     1     1   D     1     0  ...
Brentford      18/08/2024  Crystal Palace     2     1   H     1     0  ...
               31/08/2024     Southampton     3     1   H     1     0  ...
Brighton       14/09/2024         Ipswich     0     0   D     0     0  ...
               24/08/2024      Man United     2     1   H     1     0  ...
Chelsea        01/09/2024  Crystal Palace     1     1   D     1     0  ...
               18/08/2024        Man City     0     2   A     0     1  ...
Crystal Palace 14/09/2024       Leicester     2     2   D     0     1  ...
               24/08/2024        West Ham     0     2   A     0     0  ...
Everton        17/08/2024        Brighton     0     3   A     0     1  ...
               31/08/2024     Bournemouth     2     3   A     0     0  ...
Fulham         14/09/2024        West Ham     1     1   D     1     0  ...
               24/08/2024       Leicester     2     1   H     1     1  ...
Ipswich        17/08/2024       Liverpool     0     2   A     0     0  ...
               31/08/2024          Fulham     1     1   D     1     1  ...
Leicester      19/08/2024       Tottenham     1     1   D     0     1  ...
               31/08/2024     Aston Villa     1     2   A     0     1  ...
Liverpool      14/09/2024   Nott'm Forest     0     1   A     0     0  ...
               25/08/2024       Brentford     2     0   H     1     0  ...
Man City       14/09/2024       Brentford     2     1   H     2     1  ...
               24/08/2024         Ipswich     4     1   H     3     1  ...
Man United     01/09/2024       Liverpool     0     3   A     0     2  ...
               16/08/2024          Fulham     1     0   H     0     0  ...
Newcastle      01/09/2024       Tottenham     2     1   H     1     0  ...
               17/08/2024     Southampton     1     0   H     1     0  ...
Nott'm Forest  17/08/2024     Bournemouth     1     1   D     1     0  ...
               31/08/2024          Wolves     1     1   D     1     1  ...
Southampton    14/09/2024      Man United     0     3   A     0     2  ...
               24/08/2024   Nott'm Forest     0     1   A     0     0  ...
Tottenham      15/09/2024         Arsenal     0     1   A     0     0  ...
               24/08/2024         Everton     4     0   H     2     0  ...
West Ham       17/08/2024     Aston Villa     1     2   A     1     1  ...
               31/08/2024        Man City     1     3   A     1     2  ...
Wolves         15/09/2024       Newcastle     1     2   A     1     0  ...
               25/08/2024         Chelsea     2     6   A     2     2  ...

                          HST AST  HF  AF  HC  AC  HY  AY  HR  AR
HomeTeam       Date
Arsenal        17/08/2024   6   3  17  14   8   2   2   2   0   0
               31/08/2024   7   4  12   7   3   7   3   2   1   0
Aston Villa    14/09/2024   8   2  10  12   6   2   1   4   0   0
               24/08/2024   3   4   8  15   4   1   1   3   0   0
Bournemouth    14/09/2024   4   1  10   4   3   2   3   3   0   0
               25/08/2024   4   5  19   8   8   9   2   2   0   0
Brentford      18/08/2024   5   6   6  15   4   7   1   5   0   0
               31/08/2024   7   6  10   7   2   8   2   1   0   0
Brighton       14/09/2024   6   1  14  16   9   2   4   3   0   0
               24/08/2024   5   4   9  13   4   4   1   2   0   0
Chelsea        01/09/2024   7   3   9  13   4   5   4   2   0   0
               18/08/2024   3   5  12   9   4   3   1   1   0   0
Crystal Palace 14/09/2024   4   4  11  15   5   2   0   3   0   0
               24/08/2024   2   3   9  17   3   3   1   1   0   0
Everton        17/08/2024   1   5   8   8   1   5   1   1   1   0
               31/08/2024   8   7   6   1   8   4   2   1   0   0
Fulham         14/09/2024   5   3  15  18   3   2   2   3   0   0
               24/08/2024   6   4  14  13   7   5   2   2   0   0
Ipswich        17/08/2024   2   5   9  18   2  10   3   1   0   0
               31/08/2024   4   4  15  15   8   6   2   3   0   0
Leicester      19/08/2024   3   7  11  12   2  13   1   1   0   0
               31/08/2024   3   5  13  21   1   4   4   5   0   0
Liverpool      14/09/2024   5   3  15   6   7   2   4   4   0   0
               25/08/2024   8   2  10   7   9   4   2   3   0   0
Man City       14/09/2024   7   5   9   3  12   3   3   1   0   0
               24/08/2024   5   1   4  15  10   1   2   3   0   0
Man United     01/09/2024   3   3   7   7   5   2   4   1   0   0
               16/08/2024   5   2  12  10   7   8   2   3   0   0
Newcastle      01/09/2024   3   6  16  13   7  12   4   4   0   0
               17/08/2024   1   4  15  16   3  12   2   4   1   0
Nott'm Forest  17/08/2024   8   4  17   8   2   6   1   3   0   0
               31/08/2024   5   3  15  18   7   3   3   4   0   0
Southampton    14/09/2024   4  10  11  14   0   7   1   4   1   0
               24/08/2024   1   8  14  14   4  10   3   3   0   0
Tottenham      15/09/2024   5   4  13  10   7   6   5   3   0   0
               24/08/2024   7   1  11  15  12   5   0   0   0   0
West Ham       17/08/2024   3   3  18  11   5   3   1   2   0   0
               31/08/2024   2   8  10   3   3  11   3   2   0   0
Wolves         15/09/2024   5   6  17   6   4   7   3   3   0   0
               25/08/2024   4   8  13  13   5   5   2   3   0   0

[40 rows x 24 columns]