In [2]:
!pip install -Uqq fastai
!pip install -Uqq fastbook

In [3]:
import pandas as pd

In [4]:
train_org = pd.read_csv("data/titanic/train.csv")

In [53]:
# train_org.drop("Name", axis=1)
df = train_org.drop(columns = ["Name", "PassengerId", "Ticket", "Cabin"], axis=1)

In [54]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [56]:
df = df.dropna(subset=['Age', 'Embarked'])
df = df.reset_index(drop=True)
df = df[df['Fare'] != 0]
df = df.reset_index(drop=True)

In [57]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
700         0       3  female  39.0      0      5  29.1250        Q
701         0       2    male  27.0      0      0  13.0000        S
702         1       1  female  19.0      0      0  30.0000        S
703         1       1    male  26.0      0      0  30.0000        C
704         0       3    male  32.0      0      0   7.7500        Q

[705 rows x 8 columns]

In [58]:
df["Male"] = (df["Sex"] == "male").astype(int)

In [59]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Male
0           0       3    male  22.0      1      0   7.2500        S     1
1           1       1  female  38.0      1      0  71.2833        C     0
2           1       3  female  26.0      0      0   7.9250        S     0
3           1       1  female  35.0      1      0  53.1000        S     0
4           0       3    male  35.0      0      0   8.0500        S     1
..        ...     ...     ...   ...    ...    ...      ...      ...   ...
700         0       3  female  39.0      0      5  29.1250        Q     0
701         0       2    male  27.0      0      0  13.0000        S     1
702         1       1  female  19.0      0      0  30.0000        S     0
703         1       1    male  26.0      0      0  30.0000        C     1
704         0       3    male  32.0      0      0   7.7500        Q     1

[705 rows x 9 columns]

In [60]:
df["EmbarkedS"] = (df["Embarked"] == "S").astype(int)

In [61]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Male,EmbarkedS
0,0,3,male,22.0,1,0,7.2500,S,1,1
1,1,1,female,38.0,1,0,71.2833,C,0,0
2,1,3,female,26.0,0,0,7.9250,S,0,1
3,1,1,female,35.0,1,0,53.1000,S,0,1
4,0,3,male,35.0,0,0,8.0500,S,1,1
...,...,...,...,...,...,...,...,...,...,...
700,0,3,female,39.0,0,5,29.1250,Q,0,0
701,0,2,male,27.0,0,0,13.0000,S,1,1
702,1,1,female,19.0,0,0,30.0000,S,0,1
703,1,1,male,26.0,0,0,30.0000,C,1,0
704,0,3,male,32.0,0,0,7.7500,Q,1,0

In [62]:
df["EmbarkedC"] = (df["Embarked"] == "C").astype(int)

In [63]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Male,EmbarkedS,EmbarkedC
0,0,3,male,22.0,1,0,7.2500,S,1,1,0
1,1,1,female,38.0,1,0,71.2833,C,0,0,1
2,1,3,female,26.0,0,0,7.9250,S,0,1,0
3,1,1,female,35.0,1,0,53.1000,S,0,1,0
4,0,3,male,35.0,0,0,8.0500,S,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
700,0,3,female,39.0,0,5,29.1250,Q,0,0,0
701,0,2,male,27.0,0,0,13.0000,S,1,1,0
702,1,1,female,19.0,0,0,30.0000,S,0,1,0
703,1,1,male,26.0,0,0,30.0000,C,1,0,1
704,0,3,male,32.0,0,0,7.7500,Q,1,0,0

In [64]:
df["Pclass_1"] = (df["Pclass"] == 1).astype(int)
df["Pclass_2"] = (df["Pclass"] == 2).astype(int)

In [65]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Male,EmbarkedS,EmbarkedC,Pclass_1,Pclass_2
0,0,3,male,22.0,1,0,7.2500,S,1,1,0,0,0
1,1,1,female,38.0,1,0,71.2833,C,0,0,1,1,0
2,1,3,female,26.0,0,0,7.9250,S,0,1,0,0,0
3,1,1,female,35.0,1,0,53.1000,S,0,1,0,1,0
4,0,3,male,35.0,0,0,8.0500,S,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,0,3,female,39.0,0,5,29.1250,Q,0,0,0,0,0
701,0,2,male,27.0,0,0,13.0000,S,1,1,0,0,1
702,1,1,female,19.0,0,0,30.0000,S,0,1,0,1,0
703,1,1,male,26.0,0,0,30.0000,C,1,0,1,1,0
704,0,3,male,32.0,0,0,7.7500,Q,1,0,0,0,0

In [66]:
max_age = df["Age"].max()
max_age
df["AgeN"] = df["Age"] / max_age
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Male,EmbarkedS,EmbarkedC,Pclass_1,Pclass_2,AgeN
0,0,3,male,22.0,1,0,7.2500,S,1,1,0,0,0,0.2750
1,1,1,female,38.0,1,0,71.2833,C,0,0,1,1,0,0.4750
2,1,3,female,26.0,0,0,7.9250,S,0,1,0,0,0,0.3250
3,1,1,female,35.0,1,0,53.1000,S,0,1,0,1,0,0.4375
4,0,3,male,35.0,0,0,8.0500,S,1,1,0,0,0,0.4375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,0,3,female,39.0,0,5,29.1250,Q,0,0,0,0,0,0.4875
701,0,2,male,27.0,0,0,13.0000,S,1,1,0,0,1,0.3375
702,1,1,female,19.0,0,0,30.0000,S,0,1,0,1,0,0.2375
703,1,1,male,26.0,0,0,30.0000,C,1,0,1,1,0,0.3250
704,0,3,male,32.0,0,0,7.7500,Q,1,0,0,0,0,0.4000

In [67]:
import numpy as np
df['log_Fare'] = np.log(df['Fare'])
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Male,EmbarkedS,EmbarkedC,Pclass_1,Pclass_2,AgeN,log_Fare
0,0,3,male,22.0,1,0,7.2500,S,1,1,0,0,0,0.2750,1.981001
1,1,1,female,38.0,1,0,71.2833,C,0,0,1,1,0,0.4750,4.266662
2,1,3,female,26.0,0,0,7.9250,S,0,1,0,0,0,0.3250,2.070022
3,1,1,female,35.0,1,0,53.1000,S,0,1,0,1,0,0.4375,3.972177
4,0,3,male,35.0,0,0,8.0500,S,1,1,0,0,0,0.4375,2.085672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,0,3,female,39.0,0,5,29.1250,Q,0,0,0,0,0,0.4875,3.371597
701,0,2,male,27.0,0,0,13.0000,S,1,1,0,0,1,0.3375,2.564949
702,1,1,female,19.0,0,0,30.0000,S,0,1,0,1,0,0.2375,3.401197
703,1,1,male,26.0,0,0,30.0000,C,1,0,1,1,0,0.3250,3.401197
704,0,3,male,32.0,0,0,7.7500,Q,1,0,0,0,0,0.4000,2.047693

In [71]:
x = df[["SibSp", "Parch", "Male", "EmbarkedS", "EmbarkedC", "Pclass_1", "Pclass_2", "AgeN", "log_Fare"]].copy()
x["Ones"] = 1
x

,SibSp,Parch,Male,EmbarkedS,EmbarkedC,Pclass_1,Pclass_2,AgeN,log_Fare,Ones
0,1,0,1,1,0,0,0,0.2750,1.981001,1
1,1,0,0,0,1,1,0,0.4750,4.266662,1
2,0,0,0,1,0,0,0,0.3250,2.070022,1
3,1,0,0,1,0,1,0,0.4375,3.972177,1
4,0,0,1,1,0,0,0,0.4375,2.085672,1
...,...,...,...,...,...,...,...,...,...,...
700,0,5,0,0,0,0,0,0.4875,3.371597,1
701,0,0,1,1,0,0,1,0.3375,2.564949,1
702,0,0,0,1,0,1,0,0.2375,3.401197,1
703,0,0,1,0,1,1,0,0.3250,3.401197,1
704,0,0,1,0,0,0,0,0.4000,2.047693,1

In [73]:
import torch
params1 = torch.rand(10) - 0.5
params1

tensor([ 0.0204, -0.4850, -0.1373, -0.0883,  0.4425, -0.2914,  0.1904, -0.2659,
         0.0048, -0.4909])