In [7]:
# pandas Series is a one-dimensional array-like object containing a sequence of values of the same type and an associated array of data labels called index
import pandas as pd
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
# We can get array and index from Series as follows:
obj.array, obj.index

(<NumpyExtensionArray>
 [4, 7, -5, 3]
 Length: 4, dtype: int64,
 RangeIndex(start=0, stop=4, step=1))

In [9]:
# We can specify index when creating series
obj2 = pd.Series([4,7,-5,3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
# We can select multiple valuse from Series by index
obj2[["c", "a", "d"]]

c    3
a   -5
d    4
dtype: int64

In [11]:
# Numpy functions or numpy like operations can be done on the series and it will preserve the index
import numpy as np

np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
# Another way to think about series objects is as a fix length, ordered dictonary of index values to data values:
"b" in obj2, "e" in obj2

(True, False)

In [13]:
# Series can be created from Python dictionary
# Series can be converted back to dict with to_dict method
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

obj3 = pd.Series(sdata)
obj3, obj3.to_dict()

(Ohio      35000
 Texas     71000
 Oregon    16000
 Utah       5000
 dtype: int64,
 {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000})

In [14]:
# By default the index order in series will respect the order in the keys accordinf to the dictionary keys method which takes keys as they were inserted. This can be overwritten. 
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [15]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [17]:
# Series have above methods also as class methods
obj4.isna(), obj4.notna()

(California     True
 Ohio          False
 Oregon        False
 Texas         False
 dtype: bool,
 California    False
 Ohio           True
 Oregon         True
 Texas          True
 dtype: bool)

In [19]:
# Series automatically aligns in arithmetic operations by index.
# This means if for example you add a series to a series the operation will happen on elements with same index
obj3, obj4, obj3+obj4

(Ohio      35000
 Texas     71000
 Oregon    16000
 Utah       5000
 dtype: int64,
 California        NaN
 Ohio          35000.0
 Oregon        16000.0
 Texas         71000.0
 dtype: float64,
 California         NaN
 Ohio           70000.0
 Oregon         32000.0
 Texas         142000.0
 Utah               NaN
 dtype: float64)

In [23]:
# A Series index can be assigned 
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj.name = "People"
obj.index.name = "People names"
obj

People names
Bob      4
Steve    7
Jeff    -5
Ryan     3
Name: People, dtype: int64

## Data Frame
Data frame represents rectangular table of data and contains ordered named collection of colums, each of which can be a different data type. The data frame has both row and column indexes. It can thought of as a dictionary of Series all sharing the same index.

In [25]:
# There are manu ways to construct a data frama but one of the most common ones is from a dictionary of equal length lists or numpy arrays.
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [26]:
# Ther are methods
frame.head(), frame.tail()

(    state  year  pop
 0    Ohio  2000  1.5
 1    Ohio  2001  1.7
 2    Ohio  2002  3.6
 3  Nevada  2001  2.4
 4  Nevada  2002  2.9,
     state  year  pop
 1    Ohio  2001  1.7
 2    Ohio  2002  3.6
 3  Nevada  2001  2.4
 4  Nevada  2002  2.9
 5  Nevada  2003  3.2)

In [30]:
# If sequence of columns is specified in the constructor the data frame columns would be ordered as specified
frame = pd.DataFrame(data, columns=["year", "state", "pop"])
frame

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [41]:
# If a coulumn specified in the columns param of the constructior is not in the map the data for the column in data frame will be NaN
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "dept", "ppl"])
frame2, frame2.columns

(   year   state  pop dept  ppl
 0  2000    Ohio  1.5  NaN  NaN
 1  2001    Ohio  1.7  NaN  NaN
 2  2002    Ohio  3.6  NaN  NaN
 3  2001  Nevada  2.4  NaN  NaN
 4  2002  Nevada  2.9  NaN  NaN
 5  2003  Nevada  3.2  NaN  NaN,
 Index(['year', 'state', 'pop', 'dept', 'ppl'], dtype='object'))

In [42]:
# Columns can be modified by assignment
frame2["dept"] = np.arange(6.)
frame2["ppl"] = 10000
frame2

   year   state  pop  dept    ppl
0  2000    Ohio  1.5   0.0  10000
1  2001    Ohio  1.7   1.0  10000
2  2002    Ohio  3.6   2.0  10000
3  2001  Nevada  2.4   3.0  10000
4  2002  Nevada  2.9   4.0  10000
5  2003  Nevada  3.2   5.0  10000

In [43]:
# List of values must mach the length of the DataFrame to assign it to the DataFrame. If Series is assigned to DataFrame column the elements will be alligned by DataFrame index.

val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
frame2["dept"] = val

frame2

   year   state  pop  dept    ppl
0  2000    Ohio  1.5   NaN  10000
1  2001    Ohio  1.7   NaN  10000
2  2002    Ohio  3.6  -1.2  10000
3  2001  Nevada  2.4   NaN  10000
4  2002  Nevada  2.9  -1.5  10000
5  2003  Nevada  3.2  -1.7  10000

In [44]:
# Adding a columns
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  dept    ppl  eastern
0  2000    Ohio  1.5   NaN  10000     True
1  2001    Ohio  1.7   NaN  10000     True
2  2002    Ohio  3.6  -1.2  10000     True
3  2001  Nevada  2.4   NaN  10000    False
4  2002  Nevada  2.9  -1.5  10000    False
5  2003  Nevada  3.2  -1.7  10000    False

In [45]:
# Method del can be used to remove the columns
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'dept', 'ppl'], dtype='object')

In [48]:
# If the nested dic is passed to the constructor, outer keys are regarded as columns and inner keys as row indices:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},"Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [49]:
# DataFrame can be transposed, swap rows and columns in the similar way as numpy arrays
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [50]:
# If index is specified then the innder dict keys are not used 
pd.DataFrame(populations, index = [2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [61]:
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [62]:
# DataFrame method to_numpy creates two-dim numpy array
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [64]:
# If the values in the DataFrame are of different types, the type in numpy array will choosen to accomodate all.
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan, 10000],
       [2001, 'Ohio', 1.7, nan, 10000],
       [2002, 'Ohio', 3.6, -1.2, 10000],
       [2001, 'Nevada', 2.4, nan, 10000],
       [2002, 'Nevada', 2.9, -1.5, 10000],
       [2003, 'Nevada', 3.2, -1.7, 10000]], dtype=object)

## Index Objects

In [65]:
# Index objects are imutable
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index[1] = "d"  # TypeError

NameError: name 'index' is not defined

In [68]:
# In addition to be array like, index also behaves as a fixed size set
frame3.columns, "Ohio" in frame3.columns, 2003 in frame3.index

(Index(['Ohio', 'Nevada'], dtype='object'), True, False)

In [69]:
# Unlike python sets, pandas indexes can contain duplicate values
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Essential Functionality